# Available Placeholders for Marked Options:
# %UUID% - Player's UUID
# %NAME% - Player's name
# %DISTANCE% - Distance walked in the maze by the player
# %KILLS% - Player's kills in the maze
# %DEATHS% - Player's deaths in the maze
# %REGIONS% - Explored regions in the maze
# %CURRENTREGION% - The current region
# %CONTAINERS% - Containers looted within the maze
# %LEVEL% - The player's current level
# %XP% - The player's current excess xp
# %NEXTXP% - The total xp of the next level
# %TOTALXP% - The player's total ever lifetime xp

# Worlds that DeathMaze is active in.
EnabledWorlds:
- Deathmaze

# Message sent to player when using /deathmaze visit
# Only placeholder is %PNAME% (Player name)
VisitMessage: '&eWelcome to Deathmaze %PNAME%, &cstay safe.'

# Sound played to player when using /deathmaze visit
# Use NONE for no sound
VisitSound: AMBIENT_CAVE

# Header for sidebar scoreboard.
# Color codes allowed
ScoreboardHeader: '&7&l&k|&c&lDeathmaze&7&l&k|'

# Format for sidebar scoreboard content.
# Color codes and placeholders allowed.
# Ensure no two lines are the same!
ScoreboardFormat:
- '&c&l%NAME%'
- '&cDistance: &7%DISTANCE%'
- '&cKills: &7%KILLS%'
- '&cDeaths: &7%DEATHS%'
- '&cLootables: &7%CONTAINERS%'
- '&cRegions: &7%REGIONS%'
- '&cCurrent Region: &7%CURRENTREGION%'
- '&cLevel: &7%LEVEL%'
- '&cNext Level: &7%XP%/%NEXTXP%'
- '&cTotal XP: &7%TOTALXP%'

# Format for staff editing scoreboard.
# Color codes and ONLY %NAME% placeholder allowed.
# Ensure no two lines are the same.
EditingScoreboardFormat:
- ' '
- '%NAME%'
- '  '
- '&eYou are now:'
- '&c&lEDITING'
- '   '

# Format for staff spectating scoreboard.
# Color codes and ONLY %NAME% placeholder allowed.
# Ensure no two lines are the same.
SpectatingScoreboardFormat:
- ' '
- '%NAME%'
- '  '
- '&eYou are now:'
- '&c&lSPECTATING'
- '   '

# Format for entries in the hologram leaderboards
# %COLOR% - The color for the leaderboard
# %NAME% - The player's name
# %NAMEUPPER% - As above in uppercase
# %NAMELOWER% - As above in lowercase
# %VALUE% - The value from the type that the leaderboard is sorted by
# %TYPE% - The type that the leaderboard is sorted by
# %TYPEUPPER% - As above in uppercase
# %TYPELOWER% - As above in lowercase
LeaderboardEntryFormat: '&f%NUMBER%&7. %COLOR%%NAME% &7- %COLOR%%VALUE% %TYPE%'

# Types that do not show their name in leaderboards when below
NoIndicatorTypesLeaderboard:
- 'DISTANCE'
- 'LEVEL'

# Seconds in between automatic leaderboard updates
# For no updates, use 0
LeaderboardUpdateInterval: 30

# The block used in previewing regions (CLIENT SIDE PREVIEW)
PreviewBlock: GLASS

# Header for region entry title
# %RNAME% - Name of the region
RegionEntryHeader: '&c&lNow entering &e&l%RNAME%'

# The time taken for the region entry title to fade in
# Must be an integer
RegionEntryTitleFadeIn: 10

# The time taken for the region entry title to fade out
# Must be an integer
RegionEntryTitleFadeOut: 10

# The time the region entry title stays on the screen before fading out
# Must be an integer
RegionEntryTitleStay: 10

# Denotes how many seconds of blindness is to be given to a player upon entering a region, 0 for no blindness
# Must be an integer
RegionEntryBlindness: 0

# Default refill time period when creating lootable containers in milliseconds.
DefaultRefillSeconds: 660

# XP earned by a player for every 100 meters walked in the maze
XPPer100M: 2

# XP earned by a player for every kill in the maze
XPPerKill: 10

# XP earned by a player dying in the maze
XPPerDeath: 0

# XP earned by a player for opening a new lootable
XPPerLootable: 15

# XP earned by a player for entering a new region
XPPerRegion: 20