# Availiable Placeholders for Marked Options:
# %UUID% - Player's UUID
# %NAME% - Player's name
# %DISTANCE% - Distance walked in the maze by the player
# %KILLS% - Player's kills in the maze
# %DEATHS% - Player's deaths in the maze
# %REGIONS% - Explored regions in the maze
# %CONTAINERS% - Containers looted within the maze

# Worlds that deathmaze is active in.
EnabledWorlds:
- world
- nether

# Header for sidebar scoreboard.
# Color codes allowed
ScoreboardHeader: '&7&l&k|&c&lDeathMaze&7&l&k|'

# Format for sidebar scoreboard content.
# Color codes and placeholders allowed.
ScoreboardFormat:
 - '&r'
 - '&bName: &e%NAME%'
 - '&bDistance: &e%DISTANCE%'
 - '&bKills: &e%KILLS%'
 - '&bDeaths: &e%DEATHS%'
 - '&bChests: &e%CONTAINERS%'
 - '&bRegions: &e%REGIONS%'

# The block used in previewing regions (CLIENT SIDE PREVIEW)
PreviewBlock: GLASS

# Header for region entry title
# %RNAME% - Name of the region
RegionEntryHeader: '&c&lNow entering &o%RNAME%'

RegionEntryTitleFadeIn: 10

RegionEntryTitleFadeOut: 10

RegionEntryTitleStay: 10

# Default refill time period when creating lootable containers in milliseconds.
DefaultRefillSeconds: 15