name: DeathMaze
depend: [WorldEdit]
softdepend: [PlaceholderAPI]
author: 615283
version: ${project.version}
website: "https://github.com/BroCraftLive/DeathMaze"
main: com.georlegacy.general.deathmaze.DeathMaze
commands:
  deathmaze:
    usage: /<command>
    aliases: [dm, dmaze, deathm, maze]